services:
    Pawellen\ListingBundle\Factory\Extensions: ~

    Pawellen\ListingBundle\Renderer\ListingRenderer:
        arguments:
            $twig: '@twig'
            $router: '@router'
            $translator: '@translator'
            $config: '%pawellen_listing%'

    Pawellen\ListingBundle\Twig\ListingExtension:
        arguments:
            $renderer: '@Pawellen\ListingBundle\Renderer\ListingRenderer'
        tags:
            - { name: twig.extension }

    pawellen.listing.listing_factory:
        class: Pawellen\ListingBundle\Factory\ListingFactory
        arguments:
            $formFactory: '@form.factory'
            $doctrine: '@doctrine'
            $extensions: '@Pawellen\ListingBundle\Factory\Extensions'
            $renderer: '@Pawellen\ListingBundle\Renderer\ListingRenderer'
            $config: '%pawellen_listing%'

    Pawellen\ListingBundle\Factory\ListingFactory: '@pawellen.listing.listing_factory'
